//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceWare
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_
    {
        public int NumOrder { get; set; }
        public Nullable<System.DateTime> DateOrder { get; set; }
        public string email_user { get; set; }
        public Nullable<int> NumArticle { get; set; }
        public Nullable<int> QteArticle { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual User_ User_ { get; set; }
    }
}
