//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceWare.API
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    [KnownType(typeof(Categories))]
    [KnownType(typeof(Producers))]
    [KnownType(typeof(Suppliers))]
    [KnownType(typeof(Taxes_Level))]
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.Order_Details = new HashSet<Order_Details>();
            this.Reclamations = new HashSet<Reclamations>();
            this.Supply_Details = new HashSet<Supply_Details>();
            this.Returns = new HashSet<Returns>();
        }
        
        [DataMember]
        public int IdProduct { get; set; }
        [DataMember]
        public int IdCategory { get; set; }
        [DataMember]
        public Nullable<int> IdProducer { get; set; }
        [DataMember]
        public string Name_Product { get; set; }
        [DataMember]
        public Nullable<int> Quantity_Possessed { get; set; }
        [DataMember]
        public Nullable<decimal> Gross_Price { get; set; }
        [DataMember]
        public Nullable<int> IdSupplier { get; set; }
        [DataMember]
        public string Description_Product { get; set; }
        [DataMember]
        public Nullable<decimal> Net_Price { get; set; }
        [DataMember]
        public Nullable<int> IdTax_Level { get; set; }
        [DataMember]
        public string Image_Url { get; set; }

        [DataMember]
        public virtual Categories Categories { get; set; }
        [DataMember]
        public virtual Producers Producers { get; set; }
        [DataMember]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Details> Order_Details { get; set; }
        [DataMember]
        public virtual Suppliers Suppliers { get; set; }
        [DataMember]
        public virtual Taxes_Level Taxes_Level { get; set; }
        [DataMember]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reclamations> Reclamations { get; set; }
        [DataMember]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Supply_Details> Supply_Details { get; set; }
        [DataMember]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Returns> Returns { get; set; }
    }
}
