//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Order_Details = new HashSet<Order_Details>();
            this.Reclamations = new HashSet<Reclamation>();
            this.Supply_Details = new HashSet<Supply_Details>();
            this.Returns = new HashSet<Return>();
        }
    
        public int IdProduct { get; set; }
        public int IdCategory { get; set; }
        public Nullable<int> IdProducer { get; set; }
        public string Name_Product { get; set; }
        public Nullable<int> Quantity_Possessed { get; set; }
        public Nullable<decimal> Gross_Price { get; set; }
        public Nullable<int> IdSupplier { get; set; }
        public string Description_Product { get; set; }
        public Nullable<decimal> Net_Price { get; set; }
        public Nullable<int> IdTax_Level { get; set; }
        public string Image_Url { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Producer Producer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Details> Order_Details { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual Taxes_Level Taxes_Level { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reclamation> Reclamations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Supply_Details> Supply_Details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Return> Returns { get; set; }
    }
}
