//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reclamation
    {
        public int IdReclamation { get; set; }
        public int IdOrder { get; set; }
        public Nullable<int> IdStatus_Reclamation { get; set; }
        public int IdProduct { get; set; }
        public System.DateTime Date_reclamation { get; set; }
        public string Description_Reclamation { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
        public virtual Status_Reclamation Status_Reclamation { get; set; }
    }
}
